In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

this data set contains 146 columns - features

In [3]:
data=pd.read_csv(" .csv")
data.head()

,Team,Games,Win-Loss,Off Rank,Off Plays,Off Yards,Off Yards/Play,Off TDs,Off Yards per Game,Def Rank,...,Average Time of Possession per Game,Turnover Rank,Fumbles Recovered,Opponents Intercepted,Turnovers Gain,Fumbles Lost,Interceptions Thrown.y,Turnovers Lost,Turnover Margin,Avg Turnover Margin per Game
0,Air Force (Mountain West),13,11-2,51,881,5483,6.22,55,421.8,17,...,34:28,78,9,7,16,12,6,18,-2,-0.15
1,Akron (MAC),12,0-12,130,725,2918,4.02,14,243.2,83,...,26:29,128,6,5,11,12,14,26,-15,-1.25
2,Alabama (SEC),13,11-2,6,842,6640,7.89,76,510.8,20,...,29:59,3,11,17,28,4,6,10,18,1.38
3,Appalachian St. (Sun Belt),14,13-1,39,969,6064,6.26,65,433.1,26,...,31:19,7,10,14,24,3,6,9,15,1.07
4,Arizona (Pac-12),12,4-8,30,873,5281,6.05,42,440.1,120,...,27:24,89,4,11,15,6,12,18,-3,-0.25

In [5]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 130 entries, 0 to 129
Columns: 146 entries, Team to Avg Turnover Margin per Game
dtypes: float64(29), int64(113), object(4)
memory usage: 148.4+ KB

how to find columns with specific Type

In [7]:
object_columns=data.select_dtypes(include=['object'])
object_columns.columns

Index(['Team', 'Win-Loss', 'Time of Possession',
       'Average Time of Possession per Game'],
      dtype='object')

make separate a column data into 2 columns

In [9]:
win_loss_data=data['Win-Loss'].str.split("-",expand=True)
win_loss_data

      0   1
0    11   2
1     0  12
2    11   2
3    13   1
4     4   8
..   ..  ..
125   5   7
126   9   4
127   7   6
128  10   4
129   8   5

[130 rows x 2 columns]

In [11]:
data['Win']=win_loss_data[0]
data['Loss']=win_loss_data[1]
data

,Team,Games,Win-Loss,Off Rank,Off Plays,Off Yards,Off Yards/Play,Off TDs,Off Yards per Game,Def Rank,...,Fumbles Recovered,Opponents Intercepted,Turnovers Gain,Fumbles Lost,Interceptions Thrown.y,Turnovers Lost,Turnover Margin,Avg Turnover Margin per Game,Win,Loss
0,Air Force (Mountain West),13,11-2,51,881,5483,6.22,55,421.8,17,...,9,7,16,12,6,18,-2,-0.15,11,2
1,Akron (MAC),12,0-12,130,725,2918,4.02,14,243.2,83,...,6,5,11,12,14,26,-15,-1.25,0,12
2,Alabama (SEC),13,11-2,6,842,6640,7.89,76,510.8,20,...,11,17,28,4,6,10,18,1.38,11,2
3,Appalachian St. (Sun Belt),14,13-1,39,969,6064,6.26,65,433.1,26,...,10,14,24,3,6,9,15,1.07,13,1
4,Arizona (Pac-12),12,4-8,30,873,5281,6.05,42,440.1,120,...,4,11,15,6,12,18,-3,-0.25,4,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,West Virginia (Big 12),12,5-7,119,788,3863,4.90,28,321.9,74,...,6,8,14,5,15,20,-6,-0.50,5,7
126,Western Ky. (C-USA),13,9-4,84,900,5041,5.60,38,387.8,24,...,4,11,15,9,12,21,-6,-0.46,9,4
127,Western Mich. (MAC),13,7-6,25,916,5794,6.33,56,445.7,87,...,9,13,22,6,8,14,8,0.62,7,6
128,Wisconsin (Big Ten),14,10-4,38,963,6065,6.30,56,433.2,4,...,10,12,22,17,5,22,0,0.00,10,4
129,Wyoming (Mountain West),13,8-5,106,831,4562,5.49,38,350.9,43,...,8,12,20,6,9,15,5,0.38,8,5

drop last column

In [12]:
data=data.drop('Win-Loss',axis=1)
data

,Team,Games,Off Rank,Off Plays,Off Yards,Off Yards/Play,Off TDs,Off Yards per Game,Def Rank,Def Plays,...,Fumbles Recovered,Opponents Intercepted,Turnovers Gain,Fumbles Lost,Interceptions Thrown.y,Turnovers Lost,Turnover Margin,Avg Turnover Margin per Game,Win,Loss
0,Air Force (Mountain West),13,51,881,5483,6.22,55,421.8,17,752,...,9,7,16,12,6,18,-2,-0.15,11,2
1,Akron (MAC),12,130,725,2918,4.02,14,243.2,83,871,...,6,5,11,12,14,26,-15,-1.25,0,12
2,Alabama (SEC),13,6,842,6640,7.89,76,510.8,20,877,...,11,17,28,4,6,10,18,1.38,11,2
3,Appalachian St. (Sun Belt),14,39,969,6064,6.26,65,433.1,26,940,...,10,14,24,3,6,9,15,1.07,13,1
4,Arizona (Pac-12),12,30,873,5281,6.05,42,440.1,120,889,...,4,11,15,6,12,18,-3,-0.25,4,8
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
125,West Virginia (Big 12),12,119,788,3863,4.90,28,321.9,74,874,...,6,8,14,5,15,20,-6,-0.50,5,7
126,Western Ky. (C-USA),13,84,900,5041,5.60,38,387.8,24,835,...,4,11,15,9,12,21,-6,-0.46,9,4
127,Western Mich. (MAC),13,25,916,5794,6.33,56,445.7,87,932,...,9,13,22,6,8,14,8,0.62,7,6
128,Wisconsin (Big Ten),14,38,963,6065,6.30,56,433.2,4,839,...,10,12,22,17,5,22,0,0.00,10,4
129,Wyoming (Mountain West),13,106,831,4562,5.49,38,350.9,43,941,...,8,12,20,6,9,15,5,0.38,8,5